package UI;

import Model.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author naman
 */
public class SignupFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public SignupFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        mainPanel = new javax.swing.JPanel();
        lPanel = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        rPanel = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblInvalid = new javax.swing.JLabel();
        txtPswrdCon = new javax.swing.JPasswordField();
        txtPswrd = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lPanel.setBackground(new java.awt.Color(121, 237, 39));
        lPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/balanced-diet_256x256.png"))); // NOI18N
        lPanel.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 270));

        mainPanel.add(lPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        rPanel.setBackground(new java.awt.Color(255, 255, 255));
        rPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtEmail.setText("Enter Email Address");
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        rPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 200, 30));

        txtUname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtUname.setText("Enter Username");
        txtUname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtUname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnameFocusLost(evt);
            }
        });
        rPanel.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 200, 30));

        lblTitle.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(121, 237, 39));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("My HEALTH Buddy");
        rPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 100));

        lblInvalid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblInvalid.setForeground(new java.awt.Color(255, 51, 51));
        lblInvalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rPanel.add(lblInvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 380, 20));

        txtPswrdCon.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPswrdCon.setText("Confirm Password");
        txtPswrdCon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPswrdCon.setEchoChar('\u0000');
        txtPswrdCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPswrdConFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPswrdConFocusLost(evt);
            }
        });
        rPanel.add(txtPswrdCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, 30));

        txtPswrd.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPswrd.setText("Enter Password");
        txtPswrd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPswrd.setEchoChar('\u0000');
        txtPswrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPswrdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPswrdFocusLost(evt);
            }
        });
        rPanel.add(txtPswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, 30));

        mainPanel.add(rPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 400, 500));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        String username = txtUname.getText();
        String password = txtPswrdCon.getText();
        String confirmpassword = txtPswrdCon.getText();
        String email = txtEmail.getText();

        if (username.equals("Enter Username") || password.equals("Enter Password") 
                || confirmpassword.equals("Confirm Password") || email.equals("Enter Email Address")){
            lblInvalid.setText("Please fill all the fields!");
        }
        else if (!password.equals(confirmpassword)){
            lblInvalid.setText("Password does not match!");
        }
        else{
            userSignup(username,password,email);
        }

    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtPswrdConFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPswrdConFocusGained
        // TODO add your handling code here:
        if ("Confirm Password".equals(txtPswrdCon.getText())){
            txtPswrdCon.setText(null);
            txtPswrdCon.requestFocus();
            txtPswrdCon.setEchoChar('*');
        }
    }//GEN-LAST:event_txtPswrdConFocusGained

    private void txtPswrdConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPswrdConFocusLost
        // TODO add your handling code here:
        if(txtPswrdCon.getText().length()==0){
            txtPswrdCon.setText("Confirm Password");
            txtPswrdCon.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtPswrdConFocusLost

    private void txtPswrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPswrdFocusGained
        // TODO add your handling code here:
        if ("Enter Password".equals(txtPswrd.getText())){
            txtPswrd.setText(null);
            txtPswrd.requestFocus();
            txtPswrd.setEchoChar('*');
        }
    }//GEN-LAST:event_txtPswrdFocusGained

    private void txtPswrdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPswrdFocusLost
        // TODO add your handling code here:
        if(txtPswrd.getText().length()==0){
            txtPswrd.setText("Enter Password");
            txtPswrd.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtPswrdFocusLost

    private void txtUnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnameFocusGained
        // TODO add your handling code here:
        if ("Enter Username".equals(txtUname.getText())){ 
            txtUname.setText(null);
            txtUname.requestFocus();
        }
    }//GEN-LAST:event_txtUnameFocusGained

    private void txtUnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnameFocusLost
        // TODO add your handling code here:
        if(txtUname.getText().length()==0){
            txtUname.setText("Enter Username");
        }
    }//GEN-LAST:event_txtUnameFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if ("Enter Email Address".equals(txtEmail.getText())){ 
            txtEmail.setText(null);
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if(txtEmail.getText().length()==0){
            txtEmail.setText("Enter Email Address");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel lPanel;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblInvalid;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel rPanel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPswrd;
    private javax.swing.JPasswordField txtPswrdCon;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables

    private void userSignup(String username, String password, String email) {
        Connection dbconn = DBconnection.connectDB();
        try {
            PreparedStatement st = (PreparedStatement)dbconn.prepareStatement("INSERT INTO users (username,password,usertype,email) VALUES(?,?,?,?)");
            st.setString(1, username);
            st.setString(2, password);
            st.setString(3,"User");
            st.setString(4, email);
            int res = st.executeUpdate();
            lblInvalid.setText("You are all set! \n Go back to the Login page.");
            
            txtUname.setText("Enter username");
            txtPswrdCon.setText("Enter password");
            txtPswrdCon.setText("Confirm password");
            txtEmail.setText("Email address");
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
