/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Dietitian;

import UI.User.*;
import Model.People.Dietitian;
import Model.People.DietitianDirectory;
import UI.Authenticate.LoginFrame;
import UI.MainFrame;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vipul
 */
public class DietitianRegistration extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    DietitianDirectory records = new DietitianDirectory();
    private TableRowSorter sorter;
    public DietitianRegistration() {
        initComponents();
        //this.records = records;
        
//        populateTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        btnGroupDiabetes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        panelRegistration = new javax.swing.JPanel();
        panelPersonalInfo = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        comboGender = new javax.swing.JComboBox<>();
        dateDOB = new com.toedter.calendar.JDateChooser();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        panelMedical = new javax.swing.JPanel();
        comboHospital = new javax.swing.JComboBox<>();
        lblHospital = new javax.swing.JLabel();
        lblDOJ = new javax.swing.JLabel();
        dateDOJ = new com.toedter.calendar.JDateChooser();
        lblExperience = new javax.swing.JLabel();
        txtExperience = new javax.swing.JTextField();
        txtQualification = new javax.swing.JTextField();
        lblQualification = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        txtSpecialization = new javax.swing.JTextField();
        comboType = new javax.swing.JComboBox<>();
        lblType = new javax.swing.JLabel();
        txtSlots = new javax.swing.JTextField();
        lblSlots = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnView1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 179, 172));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("USER DASHBOARD");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout)
                    .addComponent(btnHome))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(66, 179, 172));

        tabbedPane.setBackground(new java.awt.Color(255, 204, 204));
        tabbedPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabbedPane.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        panelRegistration.setBackground(new java.awt.Color(66, 179, 172));

        panelPersonalInfo.setBackground(new java.awt.Color(255, 255, 255, 85));
        panelPersonalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });

        lblGender.setText("Gender:");

        lblDOB.setText("DOB:");

        lblContact.setText("Contact:");

        lblName.setText("Name:");

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Non-Binary", "Other" }));
        comboGender.setSelectedIndex(-1);

        dateDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateDOBKeyTyped(evt);
            }
        });

        lblAge.setText("Age:");

        txtAge.setEditable(false);
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });

        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });

        lblAddress.setText("Address:");

        javax.swing.GroupLayout panelPersonalInfoLayout = new javax.swing.GroupLayout(panelPersonalInfo);
        panelPersonalInfo.setLayout(panelPersonalInfoLayout);
        panelPersonalInfoLayout.setHorizontalGroup(
            panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalInfoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGender)
                    .addComponent(lblName)
                    .addComponent(lblDOB)
                    .addComponent(lblContact)
                    .addComponent(lblAddress))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress)
                    .addComponent(txtContact)
                    .addComponent(txtName)
                    .addComponent(comboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPersonalInfoLayout.createSequentialGroup()
                        .addComponent(dateDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPersonalInfoLayout.setVerticalGroup(
            panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB)
                    .addGroup(panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAge)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelMedical.setBackground(new java.awt.Color(255, 255, 255, 85));
        panelMedical.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 10))); // NOI18N

        comboHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));

        lblHospital.setText("Hospital:");

        lblDOJ.setText("DOJ:");

        dateDOJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateDOJKeyTyped(evt);
            }
        });

        lblExperience.setText("Experience(years):");

        txtExperience.setEditable(false);
        txtExperience.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExperienceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExperienceKeyTyped(evt);
            }
        });

        txtQualification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQualificationKeyTyped(evt);
            }
        });

        lblQualification.setText("Qualification:");

        lblSpecialization.setText("Specialization:");

        txtSpecialization.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSpecializationKeyTyped(evt);
            }
        });

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));

        lblType.setText("Type:");

        txtSlots.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSlotsKeyTyped(evt);
            }
        });

        lblSlots.setText("Slots:");

        javax.swing.GroupLayout panelMedicalLayout = new javax.swing.GroupLayout(panelMedical);
        panelMedical.setLayout(panelMedicalLayout);
        panelMedicalLayout.setHorizontalGroup(
            panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedicalLayout.createSequentialGroup()
                .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMedicalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblHospital))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMedicalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpecialization, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblType, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblQualification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSlots, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSlots)
                    .addGroup(panelMedicalLayout.createSequentialGroup()
                        .addComponent(dateDOJ, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(lblExperience)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboHospital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQualification, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSpecialization)
                    .addComponent(comboType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMedicalLayout.setVerticalGroup(
            panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedicalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateDOJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOJ)
                    .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblExperience)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQualification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialization))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSlots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSlots))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnRegister.setBackground(new java.awt.Color(51, 51, 51));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(51, 51, 51));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnView1.setBackground(new java.awt.Color(51, 51, 51));
        btnView1.setForeground(new java.awt.Color(255, 255, 255));
        btnView1.setText("View Details");
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrationLayout = new javax.swing.GroupLayout(panelRegistration);
        panelRegistration.setLayout(panelRegistrationLayout);
        panelRegistrationLayout.setHorizontalGroup(
            panelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrationLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(panelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrationLayout.createSequentialGroup()
                        .addGroup(panelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelMedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrationLayout.createSequentialGroup()
                        .addComponent(btnRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnView1)
                        .addGap(226, 226, 226))))
        );

        panelRegistrationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnRegister});

        panelRegistrationLayout.setVerticalGroup(
            panelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnView1)
                    .addComponent(btnRegister))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Registration", panelRegistration);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
       
        
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        char typedName = evt.getKeyChar();
        if(!Character.isAlphabetic(typedName) && !Character.isWhitespace(typedName)){
            evt.consume();
        }
        //Restrict the length to 256 
        if(txtName.getText().length() > 255){
                evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
        // TODO add your handling code here:
        char typedPhoneNumber = evt.getKeyChar();
        if(!Character.isDigit(typedPhoneNumber)){
            evt.consume();
        }
        //Restrict the length to 10 
        if(txtContact.getText().length() > 9){
                evt.consume();
        }
    }//GEN-LAST:event_txtContactKeyTyped
    
    public void resetForm(){
        
        txtName.setText(null);
        dateDOB.setDate(null);
        txtAge.setText(null);
        txtContact.setText(null);
        comboGender.setSelectedIndex(-1);
        txtAddress.setText(null);
        
        comboHospital.setSelectedIndex(-1);
        dateDOJ.setDate(null);
        txtExperience.setText(null);
        txtQualification.setText(null);
        txtSpecialization.setText(null);
        comboType.setSelectedIndex(-1);
        txtSlots.setText(null);
         
    }
    
    
    public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
        return dateToConvert.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        if(true){
            //Personal Info
            String name = txtName.getText();
            Date dob = dateDOB.getDate();
            LocalDate today = LocalDate.now();
            int age = Period.between(convertToLocalDateViaInstant(dob), today).getYears();
            System.out.print(age);
            String gender = comboGender.getSelectedItem().toString();
            long contact = Long.parseLong(txtContact.getText());
            //add line for photo (ImageIcon)

           //Address
           String address = txtAddress.getText();
           
           //Health details
           String hospital = comboHospital.getSelectedItem().toString();
           String qualification = txtQualification.getText();
           String specialization = txtSpecialization.getText();
           
           Date doj = dateDOJ.getDate();
           int experience = Period.between(convertToLocalDateViaInstant(doj), today).getYears();
           String type = comboType.getSelectedItem().toString();
           int slots = Integer.parseInt(txtSlots.getText());
                      
           Dietitian dietitian = records.addNewDietitian(name,  dob,  age,  gender,  contact,  address,  doj,  experience, qualification,  specialization,  slots,  hospital,  type);

           dietitian.setName(name);
           dietitian.setGender(gender);
           dietitian.setPhNumber(contact);
           dietitian.setAge(age);
           dietitian.setAddress(address);
           
           //Profession
           dietitian.setAssociatedHospital(hospital);
           dietitian.setDoj(doj);
           dietitian.setExperience(experience);
           dietitian.setQualification(qualification);
           dietitian.setSpecialization(specialization);
           dietitian.setType(type);
           dietitian.setSlotsAvailable(slots);
           
           JOptionPane.showMessageDialog(this, "Account Information Upodated");

           resetForm();

           System.out.println(gender);
//           populateTableData();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        resetForm();
        DietitianRegistration frame = new DietitianRegistration();
        frame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginFrame newLoginPage = new LoginFrame();
        newLoginPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        MainFrame frame = new MainFrame();
        frame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyTyped

    private void dateDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateDOBKeyTyped
        // TODO add your handling code here:
        Date dob = dateDOB.getDate();
        LocalDate today = LocalDate.now();
        int age = Period.between(convertToLocalDateViaInstant(dob), today).getYears();
        txtAge.setText(String.valueOf(age));
    }//GEN-LAST:event_dateDOBKeyTyped

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnView1ActionPerformed

    private void dateDOJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateDOJKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dateDOJKeyTyped

    private void txtExperienceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExperienceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienceKeyReleased

    private void txtExperienceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExperienceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienceKeyTyped

    private void txtQualificationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQualificationKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualificationKeyTyped

    private void txtSpecializationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpecializationKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecializationKeyTyped

    private void txtSlotsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSlotsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlotsKeyTyped
    
    boolean isDataValid(){
//        String id, name, emailId, gender, community, city, state, username ;
//        String houseNumber, zipCode, age, bloodGroup, height, weight;
//        String contactDetails;
////        Date dob;
//        //String patternEmail = "^[A-Za-z0-9+_.-]+@(.+)$";
//        String patternEmail = "^[(a-zA-Z-0-9-\\_\\+\\.)]+@[(a-z-A-z)]+\\.[(a-zA-z)]{2,3}$";
//        String bmi = "[(0-9\\.)]{2,}$";
//               
//        id = txtDoctorID.getText();
//        name = txtName.getText();
//        emailId = txtEmail.getText();
//        contactDetails = txtContact.getText();
//        age = txtAge.getText();
////        dob = DOBtxt.getDate();
//        if(comboPurpose.getSelectedItem() == null){
//            houseNumber = "";
//        }
//        else{
//            houseNumber = comboPurpose.getSelectedItem().toString();
//        }
//        
//        
//        if(comboCommunity.getSelectedItem() == null){
//            community = "";
//        }
//        else{
//            community = comboCommunity.getSelectedItem().toString();
//        }
//        
//        
//        if(comboCity.getSelectedItem() == null){
//            city = "";
//        }
//        else{
//            city = comboCity.getSelectedItem().toString();
//        }
//        state = txtState.getText();
//        zipCode = txtZipCode.getText();
//        //bloodGroup = (String) patientBloodGroupTxt.getSelectedItem();
//        String qualification = txtQualification.getText();
//        String specialization = txtSpecialization.getText();
//        String slots = txtHeight.getText();
//        String password = new String(txtPassword.getText());
//        String rePassword = new String(txtPassword2.getPassword());
//        
//        
//       
//        if(comboGender.getSelectedItem() == null){
//            gender = "";
//        }
//        else{
//            gender = comboGender.getSelectedItem().toString(); 
//        }
//        
//        String hospital;
//        if(comboBloodGroup.getSelectedItem() == null){
//            hospital = "";
//        }
//        else{
//            hospital = comboBloodGroup.getSelectedItem().toString(); 
//        }
//        
//        
//        if (id.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter Patient ID");
//            return false;
//        }
//       
//        if (name.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter name");
//            return false;
//        }
//        
//        if (gender.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please select gender");
//            return false;
//        }
//        
//        if (hospital.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please select hospital");
//            return false;
//        }
//        
//        if (contactDetails.equals("") || !(txtContact.getText().length()==10))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter valid contact Number");
//            txtContact.setText("");
//           
//            return false;
//        }
//        //emailIDTxt.getText().isBlank() &&
//        if( !txtEmail.getText().matches(patternEmail)){
//                JOptionPane.showMessageDialog(this, "Please enter a valid Email.");
//                txtEmail.setText("");
//                return false;
//            }
//       
//        if (age.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter age");
//            return false;
//        }
//       
//        if (slots.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter number of slots available");
//            return false;
//        }
//        
//        if (qualification.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter qualification");
//            return false;
//        }
//        if (specialization.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter specialization");
//            return false;
//        }
       
       
//        if (zipCode.equals("") || !(txtZipCode.getText().length()==5))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter zipCode");
//            txtZipCode.setText("");
//            return false;
//        }
//       
//   
//       
//        if (password.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter password");
//            return false;
//        }
//       
//        if (rePassword.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please enter rePassword");
//            return false;
//        }
//       
//        if (!(password).equals(rePassword)){
//            JOptionPane.showMessageDialog(this, "Password doesn't match");
//            return false;
//        }
       
        return true;
       
    }
    
    private void populateTableData() {
        //Type-cast table model into default table model
//        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
//        
//        sorter = new TableRowSorter<>(model);
//      
//        //tblDisplay = new JTable(model);
//        tableView.setRowSorter(sorter);
//        //Clear the table 
//        model.setRowCount(0);
//        
//        //Iterate through the records and fill row cells
//        for(Doctor p: records.getDoctorList()){
//            
//            // Create a row object (dtype: Object, size: number of columns required)
//            Object[] row = new Object[10];
//            row[0] = p.getDoctorID();
//            row[1] = p;
//            row[2] = p.getUsername();
//            row[3] = p.getGender();
//            row[4] = p.getAge();
//            row[5] = p.getPhNumber();
//            row[6] = p.hospital.getHospitalName();
//            row[7] = p.getSlotsAvailable();
//            row[8] = p.getQualification();
//            row[9] = p.getSpecialization();
//            
//            model.addRow(row);
//                  
//        }
//        
//        //--------------
//        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
//         @Override
//         public void insertUpdate(DocumentEvent e) {
//            search(txtSearch.getText());
//         }
//         @Override
//         public void removeUpdate(DocumentEvent e) {
//            search(txtSearch.getText());
//         }
//         @Override
//         public void changedUpdate(DocumentEvent e) {
//            search(txtSearch.getText());
//         }
//         public void search(String str) {
//            if (str.length() == 0) {
//               sorter.setRowFilter(null);
//            } else {
//               sorter.setRowFilter(RowFilter.regexFilter(str));
//            }
//         }
//      });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DietitianRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup btnGroupDiabetes;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnView1;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboHospital;
    private javax.swing.JComboBox<String> comboType;
    private com.toedter.calendar.JDateChooser dateDOB;
    private com.toedter.calendar.JDateChooser dateDOJ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOJ;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblQualification;
    private javax.swing.JLabel lblSlots;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel panelMedical;
    private javax.swing.JPanel panelPersonalInfo;
    private javax.swing.JPanel panelRegistration;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtSlots;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
